<?php

function acs_sync_menu() {
	$items = array();

	$items['admin/config/content/acs-sync'] = array(
		'title' => 'AccessACS Sync Administration',
		'description' => 'Configuration for AccessACS Sync',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('acs_sync_admin_form'),
		'access arguments' => array('administer accessacs'),
		'type' => MENU_NORMAL_ITEM,
	);

	$items['acs-sync'] = array(
		'title' => 'Sync AccessACS',
		'description' => 'Sync AccessACS to Drupal Tables',
		'page callback' => 'acs_sync_sync',
		'access arguments' => array('administer accessacs'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}


function acs_sync_permission() {
	return array(
		'administer accessacs' => array(
			'title' => t('Change core settings for AccessACS integration.'),
		)
	);
}


function acs_sync_admin_form($form, &$form_state) {
	$form['acs_site_number'] = array(
		'#type' => 'textfield',
		'#title' => t('Site Number'),
		'#default_value' => variable_get('acs_site_number', ''),
		// '#description' => t('The AccessACS site number'),
		'#required' => TRUE,
	);

	$form['acs_username'] = array(
		'#type' => 'textfield',
		'#title' => t('Username'),
		'#default_value' => variable_get('acs_username', ''),
		// '#description' => t('The AccessACS site number'),
		'#required' => TRUE,
	);

	$form['acs_password'] = array(
		'#type' => 'textfield',
		'#title' => t('Password'),
		'#default_value' => variable_get('acs_password', ''),
		// '#description' => t('The AccessACS site number'),
		'#required' => TRUE,
	);

	return system_settings_form($form);
}

function acs_sync_sync()
{
	echo '<pre>hello world!!!';

	$site_number = variable_get('acs_site_number');
	$username = variable_get('acs_username');
	$password = variable_get('acs_password');

	if (empty($site_number) || empty($username) || empty($password)) {
		drupal_set_message(t('ACS auth settings not set.'), 'error');
		return;
	}

	$query_params = [
		'q' => '%',
		'pageSize' => 10,
	];

	$headers = [
		'Authorization' => 'Basic ' . base64_encode($username . ':' . $password),
	];

	// Get the first page of results.
	$result = drupal_http_request('https://secure.accessacs.com/api_accessacs_mobile/v2/' . $site_number . '/individuals?' . http_build_query($query_params), [
		'headers' => $headers,
	]);

	if ($result->code != 200) {
		drupal_set_message(t('ACS API returned an error ' . $result->code), 'error');
		return;
	}

	var_dump(json_decode($result->data));
	
}


// TODO: Sync Tables
// TODO: Views Integration