<?php
/**
 * @file
 * The ACSSync module code
 *
 * Handles the core logic of syncing AccessACS stuff to Drupal tables.
 */


/**
 * Implements hook_menu().
 */
function acssync_menu() {
  $items = array();

  $items['admin/config/content/acs-sync'] = array(
    'title' => 'AccessACS Sync Administration',
    'description' => 'Configuration for AccessACS Sync',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('acssync_admin_form'),
    'access arguments' => array('administer accessacs'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['acs-sync'] = array(
    'title' => 'Sync AccessACS',
    'description' => 'Sync AccessACS to Drupal Tables',
    'page callback' => 'acssync_sync',
    'access arguments' => array('administer accessacs'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function acssync_permission() {
  return array(
    'administer accessacs' => array(
      'title' => t('Change core settings for AccessACS integration.'),
    ),
  );
}

/**
 * Admin form callback.
 *
 * @param array  $form
 *   Drupal form
 * @param array  $form_state
 *   Drupal form state
 *
 * @return array
 *   Rendered form
 */
function acssync_admin_form($form, &$form_state) {
  $form['acs_sync_run'] = array(
    '#type' => 'submit',
    '#value' => t('Run ACS Sync'),
    '#submit' => array('acssync_sync'),
  );

  $form['acs_site_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Site Number'),
    '#default_value' => variable_get('acs_site_number', ''),
    // '#description' => t('The AccessACS site number'),
    '#required' => TRUE,
  );

  $form['acs_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => variable_get('acs_username', ''),
    // '#description' => t('The AccessACS site number'),
    '#required' => TRUE,
  );

  $form['acs_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#default_value' => variable_get('acs_password', ''),
    // '#description' => t('The AccessACS site number'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Callback for sync page.
 */
function acssync_sync() {
  module_load_include('inc', 'ACSSync', 'ACSSync.batch');
  start_acssync_batch();

}

/**
 * Implements hook_requirements().
 */
function acssync_requirements($phase) {
  $req = [];

  $req['acssync_credentials'] = [
    'title' => t('ACSSync Credentials'),
    // 'description' => t('ACSSync needs valid credentials to work.'),
  ];

  // Check to see whether the credentials exist and work.
  $site_number = variable_get('acs_site_number');
  $username = variable_get('acs_username');
  $password = variable_get('acs_password');
  if ($site_number && $username && $password) {
    // Credentials exist, check their validity.
    $acs_api = new Drupal\ACSSync\API($site_number, $username, $password);
    if ($acs_api->check_credentials()) {
      $req['acssync_credentials']['value'] = t('Credentials are set and valid.');
      $req['acssync_credentials']['severity'] = REQUIREMENT_OK;
    } else {
      $req['acssync_credentials']['value'] = t('Credentials are set but don\'t work.');
      $req['acssync_credentials']['severity'] = REQUIREMENT_WARNING;
    }
  } else {
    $req['acssync_credentials']['value'] = t('Credentials are not set.');
    $req['acssync_credentials']['severity'] = REQUIREMENT_WARNING;
  }
  
  return $req;
}
